#!/bin/bash

echo "the given parameters (or) arguments of the scripts:$@"
echo "the given parameters (or) arguments of the scripts:$*"
echo "the home directory of user is:$HOME"
echo "the workling directory of scrpit is:$PWD"
echo "to know which user is running the scripts:$USER"
echo "the file name:$0" 
echo "pId of the proceseer is :$$"
sleep 10 &
echo "the pid of last commnd processer is:$!"


